apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forge-master-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - forge.example.com
      secretName: forge-master-web-tls
  rules:
    - host: forge.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forge-master-web
                port:
                  number: 80
